title: Minimal theme
logo: assets/img/IMG_0609.jpg
description: Minimal is a theme for GitHub Pages.
title: <p align="center"> Rohit Pandey </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
